// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerContext;

#nullable disable

namespace SqlServerContext.Migrations.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20221202145146_KundeProjektTest")]
    partial class KundeProjektTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Projekt.Domain.ProjektModel.ProjektEntity", b =>
                {
                    b.Property<int>("ProjektID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjektID"), 1L, 1);

                    b.Property<DateTime>("EstimeretSlutDato")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OprettelsesDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjektName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SælgerID")
                        .HasColumnType("int");

                    b.HasKey("ProjektID");

                    b.ToTable("Projekt", "Projekt");
                });

            modelBuilder.Entity("StamData.Domain.Ansat.AnsatModel.AnsatEntity", b =>
                {
                    b.Property<int>("AnsatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnsatID"), 1L, 1);

                    b.Property<string>("AnsatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnsatID");

                    b.ToTable("Ansat", "Ansat");
                });

            modelBuilder.Entity("StamData.Domain.Kompetencer.KompetenceModel.KompetenceEntity", b =>
                {
                    b.Property<int>("KompetenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KompetenceID"), 1L, 1);

                    b.Property<string>("KompetenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KompetenceID");

                    b.ToTable("Kompetance", "Kompetence");
                });

            modelBuilder.Entity("StamData.Domain.Kunde.KundeModel.KundeEntity", b =>
                {
                    b.Property<int>("KundeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeID"), 1L, 1);

                    b.Property<string>("KundeAdresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundeCVR")
                        .HasColumnType("int");

                    b.Property<string>("KundeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundePostNr")
                        .HasColumnType("int");

                    b.Property<string>("KundeUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundeID");

                    b.ToTable("Kunde", "Kunde");
                });
#pragma warning restore 612, 618
        }
    }
}
