// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerContext;

#nullable disable

namespace SqlServerContext.Migrations.Migrations
{
    [DbContext(typeof(ServerContext))]
    partial class ServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnsatEntityKompetenceEntity", b =>
                {
                    b.Property<int>("AnsatteEntitiesAnsatKey")
                        .HasColumnType("int");

                    b.Property<int>("KompetenceListKompetenceKey")
                        .HasColumnType("int");

                    b.HasKey("AnsatteEntitiesAnsatKey", "KompetenceListKompetenceKey");

                    b.HasIndex("KompetenceListKompetenceKey");

                    b.ToTable("AnsatEntityKompetenceEntity");
                });

            modelBuilder.Entity("StamData.Domain.Ansat.AnsatModel.AnsatEntity", b =>
                {
                    b.Property<int>("AnsatKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnsatKey"), 1L, 1);

                    b.Property<string>("AnsatEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnsatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnsatKey");

                    b.ToTable("Ansat", "Ansat");
                });

            modelBuilder.Entity("StamData.Domain.Kompetencer.KompetenceModel.KompetenceEntity", b =>
                {
                    b.Property<int>("KompetenceKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KompetenceKey"), 1L, 1);

                    b.Property<string>("KompetenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KompetenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KompetenceKey");

                    b.ToTable("Kompetance", "Kompetence");
                });

            modelBuilder.Entity("AnsatEntityKompetenceEntity", b =>
                {
                    b.HasOne("StamData.Domain.Ansat.AnsatModel.AnsatEntity", null)
                        .WithMany()
                        .HasForeignKey("AnsatteEntitiesAnsatKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StamData.Domain.Kompetencer.KompetenceModel.KompetenceEntity", null)
                        .WithMany()
                        .HasForeignKey("KompetenceListKompetenceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
